In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
pd.set_option("max_columns",500)

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [0]:
data=pd.read_csv("churn.csv")

In [5]:
data.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity OnlineBackup  \
0  No phone service             DSL             No          Yes   
1                No             DSL            Yes           No   
2                No             DSL            Yes          Yes   
3  No phone service             DSL            Yes           No   
4                No     Fiber optic             No           No   

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0               No          No          No              No  Month-to-month   
1              Yes          No          No              No        One year   
2               No          No          No              No  Month-to-month   
3              Yes         Yes          No              No        One year   
4               No          No          No              No  Month-to-month   

  PaperlessBilling              PaymentMethod  MonthlyCharges TotalCharges  \
0              Yes           Electronic check           29.85        29.85   
1               No               Mailed check           56.95       1889.5   
2              Yes               Mailed check           53.85       108.15   
3               No  Bank transfer (automatic)           42.30      1840.75   
4              Yes           Electronic check           70.70       151.65   

  Churn  
0    No  
1    No  
2   Yes  
3    No  
4   Yes

In [6]:
data["Churn"].value_counts()

No     5174
Yes    1869
Name: Churn, dtype: int64

In [7]:
data.shape

(7043, 21)

In [0]:
from sklearn.preprocessing import LabelEncoder
labels=LabelEncoder()
data=data.apply(lambda col:labels.fit_transform(col))

In [0]:
x=data.iloc[:,1:-1].values
y=data.iloc[:,-1].values.reshape(-1,1)

In [17]:
y

array([[0],
       [0],
       [1],
       ...,
       [0],
       [1],
       [0]])

In [0]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2 , random_state=42)

In [48]:
y_train

array([[0],
       [0],
       [1],
       ...,
       [0],
       [1],
       [0]])

In [0]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)


array([[-0.60127141],
       [-0.60127141],
       [ 1.66314244],
       ...,
       [-0.60127141],
       [ 1.66314244],
       [-0.60127141]])

In [50]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [0]:
y_pred_knn=knn.predict(x_test)

In [0]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,roc_curve

In [0]:
cm_knn=confusion_matrix(y_pred_knn,y_test)
acc_knn=accuracy_score(y_pred_knn,y_test)
cr_knn=classification_report(y_pred_knn,y_test)

In [54]:
cm_knn

array([[895, 177],
       [141, 196]])

In [55]:
acc_knn

0.7743080198722498

In [56]:
print(cr_knn)

              precision    recall  f1-score   support

           0       0.86      0.83      0.85      1072
           1       0.53      0.58      0.55       337

    accuracy                           0.77      1409
   macro avg       0.69      0.71      0.70      1409
weighted avg       0.78      0.77      0.78      1409



In [57]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)
y_pred_lr=lr.predict(x_test)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [0]:
cm_lr=confusion_matrix(y_pred_lr,y_test)
acc_lr=accuracy_score(y_pred_lr,y_test)
cr_lr=classification_report(y_pred_lr,y_test)

In [59]:
cm_lr

array([[934, 160],
       [102, 213]])

In [60]:
acc_lr

0.8140525195173882

In [61]:
print(cr_lr)

              precision    recall  f1-score   support

           0       0.90      0.85      0.88      1094
           1       0.57      0.68      0.62       315

    accuracy                           0.81      1409
   macro avg       0.74      0.76      0.75      1409
weighted avg       0.83      0.81      0.82      1409



In [62]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(n_estimators=10,criterion='gini',random_state=0)
rfc.fit(x_train,y_train)
y_pred_rfc=rfc.predict(x_test)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


In [0]:
cm_rfc=confusion_matrix(y_pred_rfc,y_test)
acc_rfc=accuracy_score(y_pred_rfc,y_test)
cr_rfc=classification_report(y_pred_rfc,y_test)

In [64]:
cm_rfc

array([[943, 214],
       [ 93, 159]])

In [65]:
acc_rfc

0.7821149751596878

In [66]:
print(cr_rfc)

              precision    recall  f1-score   support

           0       0.91      0.82      0.86      1157
           1       0.43      0.63      0.51       252

    accuracy                           0.78      1409
   macro avg       0.67      0.72      0.68      1409
weighted avg       0.82      0.78      0.80      1409



In [67]:
from sklearn.svm import SVC
svc=SVC()
svc.fit(x_train,y_train)
y_pred_svc=svc.predict(x_test)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [0]:
cm_svc=confusion_matrix(y_pred_svc,y_test)
acc_svc=accuracy_score(y_pred_svc,y_test)
cr_svc=classification_report(y_pred_svc,y_test)

In [69]:
cm_svc

array([[959, 194],
       [ 77, 179]])

In [70]:
acc_svc

0.8076650106458482

In [71]:
print(cr_svc)

              precision    recall  f1-score   support

           0       0.93      0.83      0.88      1153
           1       0.48      0.70      0.57       256

    accuracy                           0.81      1409
   macro avg       0.70      0.77      0.72      1409
weighted avg       0.84      0.81      0.82      1409



In [72]:
from sklearn.naive_bayes import GaussianNB
naive=GaussianNB()
naive.fit(x_train,y_train)
y_pred_naive=naive.predict(x_test)

/usr/local/lib/python3.6/dist-packages/sklearn/naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [0]:
cm_naive=confusion_matrix(y_pred_naive,y_test)
acc_naive=accuracy_score(y_pred_naive,y_test)
cr_naive=classification_report(y_pred_naive,y_test)

In [74]:
cm_naive

array([[783,  86],
       [253, 287]])

In [75]:
acc_naive

0.759403832505323

In [76]:
print(cr_naive)

              precision    recall  f1-score   support

           0       0.76      0.90      0.82       869
           1       0.77      0.53      0.63       540

    accuracy                           0.76      1409
   macro avg       0.76      0.72      0.73      1409
weighted avg       0.76      0.76      0.75      1409



In [0]:
dataset = pd.read_csv("churn.csv")

In [0]:
X = dataset.iloc[:,1:-1]
Y = dataset.iloc[:,-1].values

In [0]:
X = pd.get_dummies(X, drop_first = True)

In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [0]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(max_depth=5, min_samples_split=4)

dt.fit(X_train,Y_train)

Y_pred_dt = dt.predict(X_test)

In [0]:
cm_svc=confusion_matrix(Y_pred_dt,Y_test)
acc_svc=accuracy_score(Y_pred_dt,Y_test)
cr_svc=classification_report(Y_pred_dt,Y_test)

In [0]:
from sklearn.tree.export import export_text
from termcolor import colored

def get_code(tree, feature_names):
        left      = tree.tree_.children_left
        right     = tree.tree_.children_right
        threshold = tree.tree_.threshold
        features  = [feature_names[i] for i in tree.tree_.feature]
        value = tree.tree_.value
        rule = ''
        def recurse(left, right, threshold, features, node, rule):
                if (threshold[node] != -2):
                    
                    if left[node] != -1:
                        rule = rule + ' and ' + features[node] + '<=' + str(np.round(threshold[node], 2)) + ' '
                        recurse (left, right, threshold, features,left[node], rule)
                    
                    if right[node] != -1:
                        end = rule.find(features[node])
                        
                        rule = rule[:end - len(' and ')]
                        
                        rule = rule + ' and ' + features[node] + '>' + str(np.round(threshold[node], 2)) + ' '
                        recurse (left, right, threshold, features,right[node], rule)
                else:
                    rule = rule[len(' and '):]
                    print(colored('if', 'magenta'), end= ' ')
                    rule = ' '.join(rule.split())
                    non_fraud, fraud = value[node].ravel()
                    
                    
                    words = rule.split('and')
                    
                    for i in range(len(words)):
                        print(colored(words[i], 'blue'), end=' ')
                        print(colored('and', 'grey'), end=' ')
                    
                    if non_fraud > fraud:
                        print(colored("then Loyal customer\n", 'green'))
                    else:
                        print(colored("then Churn customer \n", 'red'))
        recurse(left, right, threshold, features, 0, rule)

In [0]:
get_code(dt, dataset.columns[:-1])

if StreamingMovies<=0.5  and  InternetService<=0.5  and  Dependents<=7.5  and  MultipleLines<=0.5  and  Dependents<=1.5 and then Churn customer 

if StreamingMovies<=0.5  and  InternetService<=0.5  and  Dependents>1.5 and then Loyal customer

if StreamingMovies<=0.5  and  InternetService<=0.5  and  Dependents<=7.5  and  MultipleLines>0.5  and  Dependents<=1.5 and then Churn customer 

if StreamingMovies<=0.5  and  InternetService<=0.5  and  Dependents>1.5 and then Churn customer 

if StreamingMovies<=0.5  and  InternetService<=0.5  and  Dependents>7.5  and  MultipleLines<=0.5  and  tenure<=0.5 and then Loyal customer

if StreamingMovies<=0.5  and  InternetService<=0.5  and  Dependents>7.5  and  MultipleLines<=0.5  and  tenure>0.5 and then Loyal customer

if StreamingMovies<=0.5  and  InternetService<=0.5  and  Dependents>7.5  and  MultipleLines>0.5  and  Dependents<=15.5 and then Churn customer 

if StreamingMovies<=0.5  and  InternetService<=0.5  and  Dependents>15.5 and then Loyal cu

In [0]:
from sklearn import tree
import graphviz
dot_data = tree.export_graphviz(dt, out_file=None, 
                     feature_names=X.columns,  
                     class_names=['Loyal', 'Churn'],  
                     filled=True, rounded=True,  
                     special_characters=True)  
graph = graphviz.Source(dot_data)  
graph
graph.render('dt.png', view=True) 

'dt.png.pdf'